export const GET_TOPICS = "GET_TOPICS";
export const CHANGE_TOPICS_PAGE = "CHANGE_TOPICS_PAGE";
export const SET_CURRENT_LIST_TOPICS = "SET_CURRENT_LIST_TOPICS";
export const SET_TOTAL_ITEMS_TOPICS = "SET_TOTAL_ITEMS_TOPICS";
